#
# ToolChain ABIZ Lab
#
# Requirements:
#  - ENV Var VAULT_ADDR
#  - ENV Var VAULT_TOKEN with valid token to access secrets/prod/abiz/lab/*
#  - ENV Var VAULT_PATH_DOCKER_HUB
#  - ENV Var DOCKER_HUB_NAME
#  - ENV Var VAULT_PATH_DOCKER_PROD
#  - ENV Var VAULT_PATH_DOCKER_QA
#  - ENV Var DOCKER_URL_PROD
#  - ENV Var DOCKER_URL_QA
#
# roland.christen@hslu.ch
#
##

variables:
  NEXUS_REPO: http://nexus.sys.prod2.abiz.res.el.eee.intern/service/rest/v1/components?repository=abiz-lab
  VAULT_PATH: secrets/prod/abiz/lab/nexus-repo

stages:
  - build
  - release

Build:
  stage: build
  image: hub.edu.abiz.ch/sys/agents/docker:stable
  script:
    - mkdir -p dist
    - tar cfv ./dist/jass-kit.tar --exclude .git -C source/ .
  artifacts:
    paths:
      - ./jass-kit.tar

Publish to Nexus:
  stage: release
  only:
    - master
  dependencies:
    - Build
  image: hub.edu.abiz.ch/sys/agents/docker:stable
  services:
    - docker:dind
  before_script:
    - NEXUS_USER=$(vault read -field=USER $VAULT_PATH_DOCKER_HOST)
    - NEXUS_PASSWORD=$(vault read -field=PASSWORD $VAULT_PATH_DOCKER_HOST)
  script:
    - >
      curl -u $NEXUS_USER:$NEXUS_PASSWORD -X POST $NEXUS_REPO \ 
           -H "accept: application/json" -H "Content-Type: multipart/form-data" \
           -F "raw.directory=test" -F "raw.asset1=@./jass-kit.tar;type=text/plain" -F "raw.asset1.filename=afile"
